services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    image: iris-vector-search:latest
    restart: always
    command: --check-caps false
    ports:
      - "1972:1972"
      - "52773:52773"
      - "53773:53773"
    volumes:
      - ./:/irisrun/repo
      - ./src/web/index.html:/usr/irissys/csp/user/index.html
  