Class St.Vectorsearch.Demo.Msg.Movies.InfoMovieResponse Extends St.Vectorsearch.Demo.Msg.Movies.MoviesResponseBase
{

property InfoMovie As St.Vectorsearch.Demo.Msg.Movies.Movies;

Storage Default
{
<Data name="InfoMovieResponseDefaultData">
<Subscript>"InfoMovieResponse"</Subscript>
<Value name="1">
<Value>InfoMovie</Value>
</Value>
</Data>
<DefaultData>InfoMovieResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
